services:
  calm-and-steady-app:
    build:
      context: .
      args:
        BUILD_DATE: ${BUILD_DATE:-latest}
    container_name: calm-and-steady-app
    ports:
      - "904:80"
    restart: unless-stopped
